"""
==========================================
  Find the Difference (LeetCode 389)
==========================================

------------------------------------------
 Part 1: Official LeetCode Description
------------------------------------------
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1: Input: s = "abcd", t = "abcde", Output: "e"
Example 2: Input: s = "", t = "y", Output: "y"

Constraints: 0 <= s.length <= 1000, t.length == s.length + 1

------------------------------------------
 Part 2: Simpler Explanation
------------------------------------------
Someone took a word, scrambled it, and hid one extra letter inside it. Find the extra letter!

    Original (s): "abcd"
    Messed up (t): "ceabd"
    Difference: 'e'

Method: XOR Trick (Bit Manipulation)
  If you XOR two identical numbers, they cancel out to 0!
  Treat characters as numbers (ASCII).
  XOR all characters in `s` AND all characters in `t`.
  Since every character matches a pair EXCEPT the hidden extra letter, everything will cancel out to 0 except for that one letter!
"""
